// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SistemaVotacion.API.Migrations
{
    [DbContext(typeof(APIContext))]
    partial class APIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaVotacion.Modelos.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DignidadId")
                        .HasColumnType("integer");

                    b.Property<int>("IdDignidad")
                        .HasColumnType("integer");

                    b.Property<int>("IdLista")
                        .HasColumnType("integer");

                    b.Property<int?>("ListaId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCandidato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DignidadId");

                    b.HasIndex("ListaId");

                    b.ToTable("Candidato");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProvincia")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCiu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdProvincia");

                    b.ToTable("Ciudad");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Dignidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreDignidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProcesoElectoralId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcesoElectoralId");

                    b.ToTable("Dignidad");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.HistorialAcceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("CuentaBloqueada")
                        .HasColumnType("boolean");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("HistorialAcceso");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.JuntaReceptora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Genero")
                        .HasColumnType("text");

                    b.Property<int>("IdRecinto")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroJunta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("RecintosId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecintosId");

                    b.ToTable("JuntaReceptora");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Lista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProceso")
                        .HasColumnType("integer");

                    b.Property<string>("NombreLista")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroLista")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcesosId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcesosId");

                    b.ToTable("Lista");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Multimedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CandidatoId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int?>("IdCandidato")
                        .HasColumnType("integer");

                    b.Property<int?>("IdLista")
                        .HasColumnType("integer");

                    b.Property<int?>("ListaId")
                        .HasColumnType("integer");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("ListaId");

                    b.ToTable("Multimedia");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Padron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("HaVotado")
                        .HasColumnType("boolean");

                    b.Property<int>("IdProceso")
                        .HasColumnType("integer");

                    b.Property<int>("IdVotante")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcesoId")
                        .HasColumnType("integer");

                    b.Property<int?>("VotanteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcesoId");

                    b.HasIndex("VotanteId");

                    b.ToTable("Padron");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Parroquia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCiudad")
                        .HasColumnType("integer");

                    b.Property<string>("NombreParro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdCiudad");

                    b.ToTable("Parroquia");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.ProcesoElectoral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdTipoProceso")
                        .HasColumnType("integer");

                    b.Property<string>("NombreProceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TipoProcesoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoProcesoId");

                    b.ToTable("ProcesoElectoral");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreProv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Provincia");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.RecintoElectoral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DetalleRecinto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DireccionRecinto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdParroquia")
                        .HasColumnType("integer");

                    b.Property<string>("NombreRecinto")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("IdParroquia");

                    b.ToTable("RecintoElectoral");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionRol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.TipoIdentificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DetalleTipIdentifiacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("TipoIdentificacion");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.TipoProceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("NombreTipoProceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoProceso");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.TipoVoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoVoto");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoDactilar")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaExpedicion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoIdentificacion")
                        .HasColumnType("integer");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdTipoIdentificacion");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Votante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdJunta")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int?>("JuntaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.HasIndex("JuntaId");

                    b.ToTable("Votante");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.VotoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdJunta")
                        .HasColumnType("integer");

                    b.Property<int>("IdProceso")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoVoto")
                        .HasColumnType("integer");

                    b.Property<int?>("JuntaId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcesoId")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoVotoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JuntaId");

                    b.HasIndex("ProcesoId");

                    b.HasIndex("TipoVotoId");

                    b.ToTable("VotoDetalle");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Candidato", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.Dignidad", "Dignidad")
                        .WithMany("Candidatos")
                        .HasForeignKey("DignidadId");

                    b.HasOne("SistemaVotacion.Modelos.Lista", "Lista")
                        .WithMany("Candidatos")
                        .HasForeignKey("ListaId");

                    b.Navigation("Dignidad");

                    b.Navigation("Lista");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Ciudad", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.Provincia", "Provincia")
                        .WithMany("Ciudades")
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Dignidad", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.ProcesoElectoral", null)
                        .WithMany("Dignidades")
                        .HasForeignKey("ProcesoElectoralId");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.HistorialAcceso", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.Usuario", "Usuario")
                        .WithOne("HistorialAcceso")
                        .HasForeignKey("SistemaVotacion.Modelos.HistorialAcceso", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.JuntaReceptora", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.RecintoElectoral", "Recintos")
                        .WithMany("JuntasReceptoras")
                        .HasForeignKey("RecintosId");

                    b.Navigation("Recintos");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Lista", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.ProcesoElectoral", "Procesos")
                        .WithMany("Listas")
                        .HasForeignKey("ProcesosId");

                    b.Navigation("Procesos");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Multimedia", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.Candidato", "Candidato")
                        .WithMany("GaleriaMultimedia")
                        .HasForeignKey("CandidatoId");

                    b.HasOne("SistemaVotacion.Modelos.Lista", "Lista")
                        .WithMany("RecursosMultimedia")
                        .HasForeignKey("ListaId");

                    b.Navigation("Candidato");

                    b.Navigation("Lista");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Padron", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.ProcesoElectoral", "Proceso")
                        .WithMany("RegistroPadron")
                        .HasForeignKey("ProcesoId");

                    b.HasOne("SistemaVotacion.Modelos.Votante", "Votante")
                        .WithMany("ParticipacionesEnPadron")
                        .HasForeignKey("VotanteId");

                    b.Navigation("Proceso");

                    b.Navigation("Votante");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Parroquia", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.Ciudad", "Ciudad")
                        .WithMany("Parroquias")
                        .HasForeignKey("IdCiudad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudad");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.ProcesoElectoral", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.TipoProceso", "TipoProceso")
                        .WithMany("ProcesosAsociados")
                        .HasForeignKey("TipoProcesoId");

                    b.Navigation("TipoProceso");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.RecintoElectoral", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.Parroquia", "Parroquia")
                        .WithMany("Recintos")
                        .HasForeignKey("IdParroquia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parroquia");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Usuario", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVotacion.Modelos.TipoIdentificacion", "TipoIdentificacion")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdTipoIdentificacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("TipoIdentificacion");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Votante", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.Usuario", "Usuario")
                        .WithOne("Votante")
                        .HasForeignKey("SistemaVotacion.Modelos.Votante", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVotacion.Modelos.JuntaReceptora", "Junta")
                        .WithMany("Votantes")
                        .HasForeignKey("JuntaId");

                    b.Navigation("Junta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.VotoDetalle", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.JuntaReceptora", "Junta")
                        .WithMany("Votos")
                        .HasForeignKey("JuntaId");

                    b.HasOne("SistemaVotacion.Modelos.ProcesoElectoral", "Proceso")
                        .WithMany()
                        .HasForeignKey("ProcesoId");

                    b.HasOne("SistemaVotacion.Modelos.TipoVoto", "TipoVoto")
                        .WithMany("VotosAsociados")
                        .HasForeignKey("TipoVotoId");

                    b.Navigation("Junta");

                    b.Navigation("Proceso");

                    b.Navigation("TipoVoto");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Candidato", b =>
                {
                    b.Navigation("GaleriaMultimedia");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Ciudad", b =>
                {
                    b.Navigation("Parroquias");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Dignidad", b =>
                {
                    b.Navigation("Candidatos");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.JuntaReceptora", b =>
                {
                    b.Navigation("Votantes");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Lista", b =>
                {
                    b.Navigation("Candidatos");

                    b.Navigation("RecursosMultimedia");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Parroquia", b =>
                {
                    b.Navigation("Recintos");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.ProcesoElectoral", b =>
                {
                    b.Navigation("Dignidades");

                    b.Navigation("Listas");

                    b.Navigation("RegistroPadron");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Provincia", b =>
                {
                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.RecintoElectoral", b =>
                {
                    b.Navigation("JuntasReceptoras");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.TipoIdentificacion", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.TipoProceso", b =>
                {
                    b.Navigation("ProcesosAsociados");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.TipoVoto", b =>
                {
                    b.Navigation("VotosAsociados");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Usuario", b =>
                {
                    b.Navigation("HistorialAcceso");

                    b.Navigation("Votante");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Votante", b =>
                {
                    b.Navigation("ParticipacionesEnPadron");
                });
#pragma warning restore 612, 618
        }
    }
}
