// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SistemaVotacion.API.Migrations
{
    [DbContext(typeof(SistemaVotacionAPIContext))]
    partial class SistemaVotacionAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaVotacion.Modelos.ActaAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HashSeguridad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdJunta")
                        .HasColumnType("integer");

                    b.Property<int>("IdProceso")
                        .HasColumnType("integer");

                    b.Property<int?>("JuntasId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int?>("ProcesosId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSufragantesPadron")
                        .HasColumnType("integer");

                    b.Property<int>("VotosEnUrna")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JuntasId");

                    b.HasIndex("ProcesosId");

                    b.ToTable("ActasAuditorias");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdDignidad")
                        .HasColumnType("integer");

                    b.Property<int>("IdLista")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCandidato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdDignidad");

                    b.HasIndex("IdLista");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProvincia")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCiudad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdProvincia");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Dignidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreDignidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProcesoElectoralId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcesoElectoralId");

                    b.ToTable("Dignidades");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Genero", b =>
                {
                    b.Property<int>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGenero"));

                    b.Property<string>("DetalleGenero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdGenero");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.JuntaReceptora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdGenero")
                        .HasColumnType("integer");

                    b.Property<int>("IdRecinto")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroJunta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RecintosId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdGenero");

                    b.HasIndex("RecintosId");

                    b.ToTable("JuntasReceptoras");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Lista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProceso")
                        .HasColumnType("integer");

                    b.Property<string>("NombreLista")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroLista")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdProceso");

                    b.ToTable("Listas");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Multimedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int?>("IdCandidato")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("IdLista")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdCandidato");

                    b.HasIndex("IdLista");

                    b.ToTable("Multimedias");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.OpcionConsulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPregunta")
                        .HasColumnType("integer");

                    b.Property<string>("TextoOpcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdPregunta");

                    b.ToTable("OpcionConsultas");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Padron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoAcceso")
                        .HasColumnType("text");

                    b.Property<bool>("HaVotado")
                        .HasColumnType("boolean");

                    b.Property<int>("IdProceso")
                        .HasColumnType("integer");

                    b.Property<int>("IdVotante")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcesoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdVotante");

                    b.HasIndex("ProcesoId");

                    b.ToTable("Padrones");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Parroquia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCiudad")
                        .HasColumnType("integer");

                    b.Property<string>("NombreParroquia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdCiudad");

                    b.ToTable("Parroquias");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.PreguntaConsulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProceso")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroPregunta")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcesosElectoralesId")
                        .HasColumnType("integer");

                    b.Property<string>("TextoPregunta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcesosElectoralesId");

                    b.ToTable("PreguntasConsultas");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.ProcesoElectoral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdTipoProceso")
                        .HasColumnType("integer");

                    b.Property<string>("NombreProceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoProceso");

                    b.ToTable("ProcesosElectorales");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreProvincia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.RecintoElectoral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DetalleRecinto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DireccionRecinto")
                        .HasColumnType("text");

                    b.Property<int>("IdParroquia")
                        .HasColumnType("integer");

                    b.Property<string>("NombreRecinto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdParroquia");

                    b.ToTable("RecintosElectorales");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.RepresentanteJunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdJunta")
                        .HasColumnType("integer");

                    b.Property<int>("IdProceso")
                        .HasColumnType("integer");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int?>("JuntaId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcesoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("JuntaId");

                    b.HasIndex("ProcesoId");

                    b.ToTable("RepresentantesJuntas");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.ResultadoDetalleAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActaId")
                        .HasColumnType("integer");

                    b.Property<int>("IdActa")
                        .HasColumnType("integer");

                    b.Property<int?>("IdLista")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int>("VotosContabilizados")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActaId");

                    b.HasIndex("IdLista");

                    b.ToTable("ResultadosDetallesAuditorias");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionRol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.TipoIdentificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DetalleTipIdentifiacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TiposIdentificaciones");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.TipoProceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("NombreTipoProceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoProcesos");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.TipoVoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoVotos");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoDactilar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("CuentaBloqueada")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdGenero")
                        .HasColumnType("integer");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoIdentificacion")
                        .HasColumnType("integer");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdGenero");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdTipoIdentificacion");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Votante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<int>("IdJunta")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int?>("JuntaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("JuntaId");

                    b.ToTable("Votantes");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.VotoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdDignidad")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int>("IdJunta")
                        .HasColumnType("integer");

                    b.Property<int?>("IdLista")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("IdOpcion")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("IdPregunta")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int>("IdProceso")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoVoto")
                        .HasColumnType("integer");

                    b.Property<int?>("JuntaId")
                        .HasColumnType("integer");

                    b.Property<int?>("OpcionId")
                        .HasColumnType("integer");

                    b.Property<int?>("PreguntaId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcesoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdDignidad");

                    b.HasIndex("IdLista");

                    b.HasIndex("IdTipoVoto");

                    b.HasIndex("JuntaId");

                    b.HasIndex("OpcionId");

                    b.HasIndex("PreguntaId");

                    b.HasIndex("ProcesoId");

                    b.ToTable("VotoDetalles");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.ActaAuditoria", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.JuntaReceptora", "Juntas")
                        .WithMany("ActasCierre")
                        .HasForeignKey("JuntasId");

                    b.HasOne("SistemaVotacion.Modelos.ProcesoElectoral", "Procesos")
                        .WithMany("ActasGeneradas")
                        .HasForeignKey("ProcesosId");

                    b.Navigation("Juntas");

                    b.Navigation("Procesos");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Candidato", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.Dignidad", "Dignidad")
                        .WithMany("Candidatos")
                        .HasForeignKey("IdDignidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVotacion.Modelos.Lista", "Lista")
                        .WithMany("Candidatos")
                        .HasForeignKey("IdLista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dignidad");

                    b.Navigation("Lista");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Ciudad", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.Provincia", "Provincia")
                        .WithMany("Ciudades")
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Dignidad", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.ProcesoElectoral", null)
                        .WithMany("DignidadesAElegir")
                        .HasForeignKey("ProcesoElectoralId");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.JuntaReceptora", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.Genero", "Genero")
                        .WithMany("Juntas")
                        .HasForeignKey("IdGenero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVotacion.Modelos.RecintoElectoral", "Recintos")
                        .WithMany("JuntasReceptoras")
                        .HasForeignKey("RecintosId");

                    b.Navigation("Genero");

                    b.Navigation("Recintos");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Lista", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.ProcesoElectoral", "Proceso")
                        .WithMany("ListasParticipantes")
                        .HasForeignKey("IdProceso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proceso");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Multimedia", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.Candidato", "Candidato")
                        .WithMany("GaleriaMultimedia")
                        .HasForeignKey("IdCandidato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVotacion.Modelos.Lista", "Lista")
                        .WithMany("RecursosMultimedia")
                        .HasForeignKey("IdLista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("Lista");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.OpcionConsulta", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.PreguntaConsulta", "Pregunta")
                        .WithMany("OpcionesConsulta")
                        .HasForeignKey("IdPregunta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Padron", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.Votante", "Votante")
                        .WithMany("VotantesEnPadron")
                        .HasForeignKey("IdVotante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVotacion.Modelos.ProcesoElectoral", "Proceso")
                        .WithMany("PadronElectoral")
                        .HasForeignKey("ProcesoId");

                    b.Navigation("Proceso");

                    b.Navigation("Votante");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Parroquia", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.Ciudad", "Ciudad")
                        .WithMany("Parroquias")
                        .HasForeignKey("IdCiudad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudad");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.PreguntaConsulta", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.ProcesoElectoral", "ProcesosElectorales")
                        .WithMany("PreguntasConsulta")
                        .HasForeignKey("ProcesosElectoralesId");

                    b.Navigation("ProcesosElectorales");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.ProcesoElectoral", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.TipoProceso", "TipoProceso")
                        .WithMany("ProcesosAsociados")
                        .HasForeignKey("IdTipoProceso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoProceso");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.RecintoElectoral", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.Parroquia", "Parroquia")
                        .WithMany("Recintos")
                        .HasForeignKey("IdParroquia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parroquia");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.RepresentanteJunta", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.Rol", "Rol")
                        .WithMany("RepresentantesConEsteRol")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVotacion.Modelos.Usuario", "Usuario")
                        .WithMany("FuncionesComoRepresentante")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVotacion.Modelos.JuntaReceptora", "Junta")
                        .WithMany("Representantes")
                        .HasForeignKey("JuntaId");

                    b.HasOne("SistemaVotacion.Modelos.ProcesoElectoral", "Proceso")
                        .WithMany("RepresentantesMesas")
                        .HasForeignKey("ProcesoId");

                    b.Navigation("Junta");

                    b.Navigation("Proceso");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.ResultadoDetalleAuditoria", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.ActaAuditoria", "Acta")
                        .WithMany("DetallesResultados")
                        .HasForeignKey("ActaId");

                    b.HasOne("SistemaVotacion.Modelos.Lista", "Lista")
                        .WithMany()
                        .HasForeignKey("IdLista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acta");

                    b.Navigation("Lista");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Usuario", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.Genero", "Genero")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdGenero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVotacion.Modelos.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVotacion.Modelos.TipoIdentificacion", "TipoIdentificacion")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdTipoIdentificacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Rol");

                    b.Navigation("TipoIdentificacion");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Votante", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.Usuario", "Usuario")
                        .WithMany("PerfilesVotante")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVotacion.Modelos.JuntaReceptora", "Junta")
                        .WithMany("VotantesAsignados")
                        .HasForeignKey("JuntaId");

                    b.Navigation("Junta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.VotoDetalle", b =>
                {
                    b.HasOne("SistemaVotacion.Modelos.Dignidad", "Dignidad")
                        .WithMany("VotosRecibidos")
                        .HasForeignKey("IdDignidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVotacion.Modelos.Lista", "Lista")
                        .WithMany("VotosRecibidos")
                        .HasForeignKey("IdLista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVotacion.Modelos.TipoVoto", "TipoVoto")
                        .WithMany("VotosAsociados")
                        .HasForeignKey("IdTipoVoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVotacion.Modelos.JuntaReceptora", "Junta")
                        .WithMany("VotosRecibidos")
                        .HasForeignKey("JuntaId");

                    b.HasOne("SistemaVotacion.Modelos.OpcionConsulta", "Opcion")
                        .WithMany("VotosRecibidos")
                        .HasForeignKey("OpcionId");

                    b.HasOne("SistemaVotacion.Modelos.PreguntaConsulta", "Pregunta")
                        .WithMany("VotosRecibidos")
                        .HasForeignKey("PreguntaId");

                    b.HasOne("SistemaVotacion.Modelos.ProcesoElectoral", "Proceso")
                        .WithMany("VotoDetallados")
                        .HasForeignKey("ProcesoId");

                    b.Navigation("Dignidad");

                    b.Navigation("Junta");

                    b.Navigation("Lista");

                    b.Navigation("Opcion");

                    b.Navigation("Pregunta");

                    b.Navigation("Proceso");

                    b.Navigation("TipoVoto");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.ActaAuditoria", b =>
                {
                    b.Navigation("DetallesResultados");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Candidato", b =>
                {
                    b.Navigation("GaleriaMultimedia");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Ciudad", b =>
                {
                    b.Navigation("Parroquias");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Dignidad", b =>
                {
                    b.Navigation("Candidatos");

                    b.Navigation("VotosRecibidos");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Genero", b =>
                {
                    b.Navigation("Juntas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.JuntaReceptora", b =>
                {
                    b.Navigation("ActasCierre");

                    b.Navigation("Representantes");

                    b.Navigation("VotantesAsignados");

                    b.Navigation("VotosRecibidos");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Lista", b =>
                {
                    b.Navigation("Candidatos");

                    b.Navigation("RecursosMultimedia");

                    b.Navigation("VotosRecibidos");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.OpcionConsulta", b =>
                {
                    b.Navigation("VotosRecibidos");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Parroquia", b =>
                {
                    b.Navigation("Recintos");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.PreguntaConsulta", b =>
                {
                    b.Navigation("OpcionesConsulta");

                    b.Navigation("VotosRecibidos");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.ProcesoElectoral", b =>
                {
                    b.Navigation("ActasGeneradas");

                    b.Navigation("DignidadesAElegir");

                    b.Navigation("ListasParticipantes");

                    b.Navigation("PadronElectoral");

                    b.Navigation("PreguntasConsulta");

                    b.Navigation("RepresentantesMesas");

                    b.Navigation("VotoDetallados");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Provincia", b =>
                {
                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.RecintoElectoral", b =>
                {
                    b.Navigation("JuntasReceptoras");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Rol", b =>
                {
                    b.Navigation("RepresentantesConEsteRol");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.TipoIdentificacion", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.TipoProceso", b =>
                {
                    b.Navigation("ProcesosAsociados");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.TipoVoto", b =>
                {
                    b.Navigation("VotosAsociados");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Usuario", b =>
                {
                    b.Navigation("FuncionesComoRepresentante");

                    b.Navigation("PerfilesVotante");
                });

            modelBuilder.Entity("SistemaVotacion.Modelos.Votante", b =>
                {
                    b.Navigation("VotantesEnPadron");
                });
#pragma warning restore 612, 618
        }
    }
}
